"use client";

import { useEffect, useMemo, useRef, useState, type KeyboardEvent as ReactKeyboardEvent, type PointerEvent as ReactPointerEvent } from "react";
import { estimateVideoCost, VIDEO_PROVIDERS } from "@podframes/core/shared";
import { providerColor, providerOfModel } from "@/lib/providers";
import { useDraft } from "@/components/studio/useDraft";
import { mediaUrl, regenerateClips, type ClipAsset, type Host, type TurnRegion } from "@/components/studio/api";
import { useWizard } from "./context";
import { StepHeader, StepFooter } from "./ui";

const roundTrim = (n: number) => Math.round(n * 10) / 10;

export function Step3Videos() {
  const ctx = useWizard();
  const { project, slug, locked, busy, running, log } = ctx;
  const turns = project?.speech?.turns ?? [];
  const provider = project?.options?.videoProvider ?? "replicate-p-video";
  const disabled = locked || busy;
  const videoDone = project?.stages.video === "done";
  const [actionError, setActionError] = useState<string | null>(null);

  const clipByTurn = useMemo(() => new Map((project?.clips ?? []).map((c) => [c.turnIndex, c])), [project?.clips]);

  const turnIds = turns.map((t) => t.turnIndex);
  // Fresh start: everything selected, zero interaction needed. Once ANY clip
  // exists (done or a partial subset run), default to ONLY the turns without
  // one — generating can never silently redo paid clips.
  const missingIds = turnIds.filter((i) => !clipByTurn.has(i));
  const defaultSelection = clipByTurn.size > 0 ? missingIds : turnIds;
  const [selected, setSelected] = useDraft<number[]>(defaultSelection, `${turnIds.join(",")}|${clipByTurn.size > 0}`);

  // Pre-spend estimate from the selected turns' real audio durations and the
  // provider's published per-second price (shared PRICING — an estimate, not a quote).
  const resolution = project?.options?.videoResolution ?? "720p";
  const selectedSecs = turns
    .filter((t) => selected.includes(t.turnIndex))
    .reduce((a, t) => a + t.durationSec, 0);
  const estCost = estimateVideoCost(provider, resolution, selectedSecs);
  const estLabel =
    selected.length > 0
      ? `~${Math.round(selectedSecs)}s of video · ${resolution}${estCost != null ? ` · est. ~$${estCost.toFixed(2)}` : ""}`
      : null;

  // Live per-turn status straight off the run stream's TYPED clip events while a
  // run is in flight — the on-disk `clips` list catches up as partial saves land.
  const liveStatus = useMemo(() => {
    const m = new Map<number, "rendering" | "done">();
    for (const l of log) {
      if (l.stage !== "video" || !l.clip) continue;
      m.set(l.clip.turnIndex, l.clip.status);
    }
    return m;
  }, [log]);

  function toggle(i: number) {
    setSelected((s) => (s.includes(i) ? s.filter((x) => x !== i) : [...s, i]));
  }

  async function setProvider(p: "fal-ltx" | "replicate-p-video") {
    if (p === provider) return;
    // Every existing clip was made by the old provider — switching deletes them
    // all. Count only clips that map to CURRENT turns (what the grid shows), not
    // raw state entries (per-segment rows + any orphans of deleted turns).
    const clipCount = turns.filter((t) => clipByTurn.has(t.turnIndex)).length;
    if (clipCount > 0 && !(await ctx.confirm({
      title: "Switch video provider?",
      body: "Existing clips were generated by the current provider and cannot be reused by the new one.",
      details: [`Will delete ${clipCount} generated clip${clipCount === 1 ? "" : "s"}.`, "You can regenerate them with the selected provider afterward."],
      confirmLabel: "Switch provider",
      tone: "warn",
    }))) return;
    void ctx.patch({ options: { videoProvider: p } });
  }

  async function generateSelected() {
    if (!selected.length || !ctx.slug) return;
    // ALWAYS confirm before kicking off paid animation — with what it costs.
    const label = VIDEO_PROVIDERS.find((p) => p.id === provider)?.label ?? provider;
    const redoing = selected.filter((i) => clipByTurn.has(i)).length;
    if (!(await ctx.confirm({
      title: "Generate videos?",
      body: `Animate ${selected.length} clip${selected.length === 1 ? "" : "s"} with ${label} at ${resolution}.`,
      details: [
        `Duration: ~${Math.round(selectedSecs)}s of video.`,
        estCost != null ? `Estimated cost: ~$${estCost.toFixed(2)}.` : "Estimated cost unavailable for this provider.",
        ...(redoing > 0 ? [`${redoing} existing clip${redoing === 1 ? "" : "s"} will be deleted and re-animated.`] : []),
      ],
      confirmLabel: redoing > 0 ? "Regenerate clips" : "Generate videos",
      tone: redoing > 0 ? "danger" : "warn",
    }))) return;
    setActionError(null);
    try {
      // Deletes just the selected turns' existing clip files (a no-op for turns that
      // don't have one yet), then animates ONLY the selected turns — unselected turns
      // are never generated, whether or not they have a clip yet.
      await regenerateClips(ctx.slug, selected);
      await ctx.generate({ to: "video", onlyTurns: selected });
    } catch (e) {
      setActionError(e instanceof Error ? e.message : String(e));
    }
  }

  async function saveClipTrim(id: string, trimStartSec: number, trimEndSec: number) {
    setActionError(null);
    await ctx.patch({ clipTrims: [{ id, trimStartSec, trimEndSec }] });
    ctx.setClipTrimDrafts((drafts) => {
      const next = { ...drafts };
      delete next[id];
      return next;
    });
  }

  function previewClipTrim(clip: ClipAsset, trimStartSec: number, trimEndSec: number) {
    const start = roundTrim(trimStartSec);
    const end = roundTrim(trimEndSec);
    const savedStart = roundTrim(clip.trimStartSec ?? 0);
    const savedEnd = roundTrim(clip.trimEndSec ?? 0);
    ctx.setClipTrimDrafts((drafts) => {
      const next = { ...drafts };
      if (start === savedStart && end === savedEnd) delete next[clip.id];
      else next[clip.id] = { trimStartSec: start, trimEndSec: end };
      return next;
    });
  }

  return (
    <div>
      <StepHeader
        title="Generate videos"
        hint="Animate each line into a lip-synced clip. Pick a provider, then generate — check specific lines to redo just those later."
      />

      <div className="mono mb-2 text-[10px] tracking-[0.08em] text-[var(--color-text-muted)]">PROVIDER</div>
      <div className="mb-5 grid grid-cols-2 gap-1.5">
        {VIDEO_PROVIDERS.map((p) => (
          <button
            key={p.id}
            onClick={() => void setProvider(p.id)}
            disabled={disabled}
            className="border p-2.5 text-left disabled:opacity-50"
            style={{ borderColor: provider === p.id ? "var(--color-accent)" : "var(--color-hairline)" }}
          >
            <div className="flex items-center justify-between text-sm font-medium">
              {p.label}
              {provider === p.id && <span className="text-[11px] text-[var(--color-accent)]">selected</span>}
            </div>
            <div className="mt-0.5 text-[10px] text-[var(--color-text-muted)]">{p.blurb}</div>
          </button>
        ))}
      </div>

      <div className="mono mb-2 flex items-center justify-between text-[10px] tracking-[0.08em] text-[var(--color-text-muted)]">
        <span>CLIPS · {selected.length}/{turns.length} selected</span>
        <div className="flex gap-3">
          <button onClick={() => setSelected(turnIds)} disabled={disabled} className="hover:text-[var(--color-text)] disabled:opacity-40">all</button>
          <button onClick={() => setSelected([])} disabled={disabled} className="hover:text-[var(--color-text)] disabled:opacity-40">none</button>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
        {turns.map((t) => {
          const host = project?.config.hosts.find((h) => h.id === t.hostId);
          const color = host ? providerColor(providerOfModel(host.model)) : "#9AA6B2";
          const clip = clipByTurn.get(t.turnIndex);
          const status = liveStatus.get(t.turnIndex);
          const ready = !!clip && status !== "rendering";
          const isChecked = selected.includes(t.turnIndex);
          return (
            <ClipCard
              key={`${t.turnIndex}:${clip?.id ?? "none"}`}
              turn={t}
              host={host}
              color={color}
              clip={clip}
              slug={slug}
              version={project?.clipsVersion ?? undefined}
              status={status}
              ready={ready}
              checked={isChecked}
              disabled={disabled}
              onToggle={() => toggle(t.turnIndex)}
              onSaveTrim={saveClipTrim}
              onPreviewTrim={previewClipTrim}
            />
          );
        })}
      </div>

      {actionError && <div className="mt-3 text-[12px] text-[var(--color-danger)]">{actionError}</div>}

      <StepFooter>
        <div className="flex flex-col gap-1">
          <button onClick={generateSelected} disabled={disabled || selected.length === 0} className="btn btn-primary px-5 py-2 text-sm disabled:opacity-50">
            {running ? "Generating…" : videoDone ? `Regenerate selected (${selected.length})` : `Generate videos (${selected.length})`}
          </button>
          {estLabel && !running && (
            <span className="mono text-[10px] text-[var(--color-text-muted)]">{estLabel}</span>
          )}
          {videoDone && selected.some((i) => clipByTurn.has(i)) && (
            <span className="text-[10px] text-[var(--color-text-muted)]">
              deletes and re-animates {selected.filter((i) => clipByTurn.has(i)).length} existing clip(s)
            </span>
          )}
        </div>
        {videoDone && (
          <button onClick={() => ctx.go(4)} disabled={disabled} className="btn btn-ghost px-5 py-2 text-sm disabled:opacity-50">Next: B-roll →</button>
        )}
      </StepFooter>
    </div>
  );
}

function ClipCard({
  turn,
  host,
  color,
  clip,
  slug,
  version,
  status,
  ready,
  checked,
  disabled,
  onToggle,
  onSaveTrim,
  onPreviewTrim,
}: {
  turn: TurnRegion;
  host?: Host;
  color: string;
  clip?: ClipAsset;
  slug: string | null;
  version?: string | number | null;
  status?: "rendering" | "done";
  ready: boolean;
  checked: boolean;
  disabled: boolean;
  onToggle: () => void;
  onSaveTrim: (id: string, trimStartSec: number, trimEndSec: number) => Promise<void>;
  onPreviewTrim: (clip: ClipAsset, trimStartSec: number, trimEndSec: number) => void;
}) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const trimRailRef = useRef<HTMLDivElement | null>(null);
  const savedStart = clip?.trimStartSec ?? 0;
  const savedEnd = clip?.trimEndSec ?? 0;
  const [trim, setTrim] = useState({ start: savedStart, end: savedEnd });
  const trimRef = useRef(trim);
  const [saving, setSaving] = useState(false);

  const duration = clip?.durationSec ?? turn.durationSec;
  const minKeep = Math.min(0.2, Math.max(0.05, duration));
  const keptEnd = Math.max(trim.start + minKeep, duration - trim.end);
  const endAt = Math.max(trim.start + 0.1, duration - trim.end);
  const dirty = !!clip && (roundTrim(trim.start) !== roundTrim(savedStart) || roundTrim(trim.end) !== roundTrim(savedEnd));
  const hasTrim = trim.start > 0 || trim.end > 0;
  const startPct = duration > 0 ? (trim.start / duration) * 100 : 0;
  const endPct = duration > 0 ? (keptEnd / duration) * 100 : 100;

  useEffect(() => {
    const video = videoRef.current;
    if (!video || !ready || !clip) return;
    const seek = () => {
      try {
        video.currentTime = trim.start;
        void video.play().catch(() => {});
      } catch {
        /* media may not be ready yet */
      }
    };
    if (video.readyState > 0) seek();
    else video.addEventListener("loadedmetadata", seek, { once: true });
    return () => video.removeEventListener("loadedmetadata", seek);
  }, [clip, ready, trim.start, trim.end]);

  function moveTrimHandle(which: "start" | "end", value: number) {
    const prev = trimRef.current;
    const currentEnd = duration - prev.end;
    const next =
      which === "start"
        ? { ...prev, start: roundTrim(Math.max(0, Math.min(value, currentEnd - minKeep))) }
        : { ...prev, end: roundTrim(Math.max(0, duration - roundTrim(Math.min(duration, Math.max(value, prev.start + minKeep))))) };
    trimRef.current = next;
    setTrim(next);
    if (clip) onPreviewTrim(clip, next.start, next.end);
  }

  function trimValueFromPointer(clientX: number) {
    const rect = trimRailRef.current?.getBoundingClientRect();
    if (!rect || rect.width <= 0) return 0;
    const ratio = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
    return roundTrim(ratio * duration);
  }

  function startTrimDrag(which: "start" | "end", e: ReactPointerEvent) {
    if (disabled || saving) return;
    e.preventDefault();
    e.stopPropagation();
    moveTrimHandle(which, trimValueFromPointer(e.clientX));
    const onMove = (ev: PointerEvent) => moveTrimHandle(which, trimValueFromPointer(ev.clientX));
    const onUp = () => {
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
    };
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp, { once: true });
  }

  function startNearestTrimDrag(e: ReactPointerEvent) {
    if (disabled || saving) return;
    const value = trimValueFromPointer(e.clientX);
    const which = Math.abs(value - trim.start) <= Math.abs(value - keptEnd) ? "start" : "end";
    startTrimDrag(which, e);
  }

  function nudgeTrimHandle(which: "start" | "end", e: ReactKeyboardEvent<HTMLButtonElement>) {
    const step = e.shiftKey ? 0.5 : 0.1;
    const current = which === "start" ? trim.start : keptEnd;
    const next =
      e.key === "ArrowLeft" || e.key === "ArrowDown"
        ? current - step
        : e.key === "ArrowRight" || e.key === "ArrowUp"
          ? current + step
          : undefined;
    if (next == null) return;
    e.preventDefault();
    moveTrimHandle(which, next);
  }

  function loopTrimmedPreview() {
    const video = videoRef.current;
    if (!video || !clip) return;
    if (video.currentTime < trim.start || video.currentTime >= endAt) {
      video.currentTime = trim.start;
      void video.play().catch(() => {});
    }
  }

  async function save() {
    if (!clip || !dirty) return;
    const current = trimRef.current;
    setSaving(true);
    try {
      await onSaveTrim(clip.id, roundTrim(current.start), roundTrim(current.end));
    } finally {
      setSaving(false);
    }
  }

  function reset() {
    const next = { start: 0, end: 0 };
    trimRef.current = next;
    if (clip) onPreviewTrim(clip, 0, 0);
    setTrim(next);
  }

  return (
    <div className="relative flex flex-col gap-1 border p-1.5" style={{ borderColor: checked ? "var(--color-accent)" : "var(--color-hairline)" }}>
      <input
        type="checkbox"
        checked={checked}
        disabled={disabled}
        onChange={onToggle}
        className="absolute left-2 top-2 z-10 h-3.5 w-3.5"
        aria-label={`Include turn ${turn.turnIndex} (${host?.name ?? "host"})`}
      />
      <div className="aspect-video w-full overflow-hidden bg-[var(--color-surface-2)]">
        {ready && slug && clip ? (
          <video
            ref={videoRef}
            src={mediaUrl(slug, clip.path, version ?? undefined)}
            muted
            loop={!hasTrim}
            autoPlay
            playsInline
            onLoadedMetadata={loopTrimmedPreview}
            onTimeUpdate={loopTrimmedPreview}
            className="h-full w-full object-cover"
          />
        ) : status === "rendering" ? (
          <div className="grid h-full place-items-center">
            <span className="live-dot h-1.5 w-1.5 rounded-full bg-[var(--color-accent)]" />
          </div>
        ) : (
          <div className="grid h-full place-items-center text-[9px] text-[var(--color-text-muted)]">not generated</div>
        )}
      </div>
      <div className="flex items-center gap-1.5">
        <span className="h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: color }} />
        <span className="truncate text-[10px] text-[var(--color-text-muted)]">{host?.name ?? "?"} · turn {turn.turnIndex}</span>
        {clip && (
          <span className="mono ml-auto shrink-0 text-[9px] text-[var(--color-text-muted)]">{duration.toFixed(1)}s</span>
        )}
      </div>
      {ready && clip && (
        <div className="mt-1 border-t border-[var(--color-hairline)] pt-1.5">
          <div className="mono mb-1 flex items-center justify-between text-[9px] text-[var(--color-text-muted)]">
            <span>TRIM</span>
            <span>{hasTrim ? `${(duration - trim.start - trim.end).toFixed(1)}s kept` : "full clip"}</span>
          </div>
          <div className="py-1">
            <div
              ref={trimRailRef}
              onPointerDown={startNearestTrimDrag}
              className="relative h-5 touch-none"
              aria-label={`Trim range for turn ${turn.turnIndex}`}
            >
              <div className="absolute inset-x-0 top-1/2 h-1 -translate-y-1/2 bg-[var(--color-surface-2)]" />
              <div
                className="absolute top-1/2 h-1 -translate-y-1/2 bg-[var(--color-accent)]"
                style={{ left: `${startPct}%`, width: `${Math.max(0, endPct - startPct)}%` }}
              />
              <button
                type="button"
                role="slider"
                aria-label={`Trim start for turn ${turn.turnIndex}`}
                aria-valuemin={0}
                aria-valuemax={roundTrim(Math.max(0, keptEnd - minKeep))}
                aria-valuenow={roundTrim(trim.start)}
                disabled={disabled || saving}
                onPointerDown={(e) => startTrimDrag("start", e)}
                onKeyDown={(e) => nudgeTrimHandle("start", e)}
                className="absolute top-1/2 h-4 w-2 -translate-x-1/2 -translate-y-1/2 border border-[var(--color-accent)] bg-[var(--color-bg)] disabled:opacity-40"
                style={{ left: `${startPct}%` }}
              />
              <button
                type="button"
                role="slider"
                aria-label={`Trim end for turn ${turn.turnIndex}`}
                aria-valuemin={roundTrim(trim.start + minKeep)}
                aria-valuemax={roundTrim(duration)}
                aria-valuenow={roundTrim(keptEnd)}
                disabled={disabled || saving}
                onPointerDown={(e) => startTrimDrag("end", e)}
                onKeyDown={(e) => nudgeTrimHandle("end", e)}
                className="absolute top-1/2 h-4 w-2 -translate-x-1/2 -translate-y-1/2 border border-[var(--color-accent)] bg-[var(--color-bg)] disabled:opacity-40"
                style={{ left: `${endPct}%` }}
              />
            </div>
            <div className="mono flex items-center justify-between text-[9px] text-[var(--color-text-muted)]">
              <span>in +{trim.start.toFixed(1)}</span>
              <span>out -{trim.end.toFixed(1)}</span>
            </div>
          </div>
          <div className="mt-1 flex items-center justify-between gap-2">
            <button
              type="button"
              disabled={disabled || saving || (!hasTrim && !dirty)}
              onClick={reset}
              className="mono text-[9px] text-[var(--color-text-muted)] hover:text-[var(--color-text)] disabled:opacity-40"
            >
              reset
            </button>
            <button
              type="button"
              disabled={disabled || saving || !dirty}
              onClick={() => void save()}
              className="mono text-[9px] text-[var(--color-accent)] hover:text-[var(--color-text)] disabled:opacity-40"
            >
              {saving ? "saving" : "save trim"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
